apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deploy
  labels:
    name: mssql-deploy
    app: app
spec:
    replicas: 1
    selector:
      matchLabels:
        app: app
        type: mssql-pod
    template:
      metadata:
        name: mssql-pod
        labels:
            app: app
            type: mssql-pod
      spec:
        containers:
          - name: mssql
            image: mcr.microsoft.com/mssql/server
            ports: 
              - containerPort: 1433
            env:
              - name: ACCEPT_EULA
                value: "Y"
              - name: SA_PASSWORD
                value: "@Marzo2021"

